### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by Swfe15** [oop7/Adobe.Acrobat.Pro-Activator#1]
Decoding encoded files...
Exception calling "FromBase64String" with "1" argument(s): "The input is not a valid Base-64 string as it contains a
non-base 64 character, more than two padding characters, or an illegal character among the padding characters. "
At line:1 char:1
+ [System.IO.File]::WriteAllBytes('C:\Users\ali0e\AppData\Local\Temp\de ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FormatException

Failed to decode file.
<img width="668" alt="Screenshot 2024-11-24 215147" src="https://github.com/user-attachments/assets/feafa3b0-242f-475e-9e77-3194bafed4ed">

**Comment by oop7** [comment]
Fixed in the latest version download it from the [release section](https://github.com/oop7/Adobe.Acrobat.Pro-Activator/releases/tag/v1.1)
